name: "Vulnerability Scan on Deployment with GitHub ACTION"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build the Action Project
        run: npm run build

      - name: Run Vulnerability Scan Action
        uses: ./
        with:
          deployment_url: ${{ steps.deploy.outputs.deployment_url }}
          github_token: ${{ secrets.GITHUB_TOKEN }}